#ifndef MINIISA_PERMISSIONS_H
#   define MINIISA_PERMISSIONS_H

#   define MINIISA_NO_PERMS (0)
#   define MINIISA_PERMS_EXECUTE (1)
#   define MINIISA_PERMS_WRITE (2)
#   define MINIISA_PERMS_READ (4)

#endif
